numpy是Python中科学计算的基础包。
它是一个Python库，提供多维数组对象、各种派生对象（例如掩码数组和矩阵）以及用于对数组进行快速操作的各种方法，包括数学、逻辑、形状操作、排序、选择、I/O、离散傅里叶变换、基本线性代数、基本统计运算、随机模拟等等。

### 一、ndarray ###

**1.ndarray的特性**

多维性：支持0维（标量）、1维（向量）、2维（矩阵）及更高维数组。

同质性：所有元素类型必须一致（通过dtype指定）。

高效性：基于连续内存块存储，支持向量化运算。

In [1]:
import numpy as np

In [5]:
arr = np.array(5) # 创建0维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim) # number of dimensions

5
arr的维度： 0


In [6]:
arr = np.array([1, 2, 3]) # 创建1维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim) # number of dimensions

[1 2 3]
arr的维度： 1


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 创建2维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim) # number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度： 2


In [9]:
arr = np.array([1, 'hello']) # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

['1' 'hello']


In [10]:
arr = np.array([1, 2.5]) # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

[1.  2.5]


**2.ndarray的属性**

shape: 数组的形状-行数和列数（或更高维度的尺寸）。

ndim: 维度数量-数组是几维的。

size: 总元素个数-数组中所有元素的总数。

dtype: 元素类型-数组中元素的类型（整数、浮点数等）。

T: 转置-行变列，列变行

itemsize: 每个元素占用的内存字节数

nbytes: 数组总内存占用量： size * itemsize

flags: 内存存储方式-是否连续存储（高级优化）

In [22]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
元素的数据类型： int64


In [27]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置', arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
元素的数据类型： float64
元素的转置 [1.  2.5 3. ]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
元素的数据类型： int64
元素的转置 [[1 4]
 [2 5]
 [3 6]]


**3.ndarray的创建**

1. 基础构造： 适用于手动构建小规模数组或复制已有数据。
2. 预定义形状填充： 用于快速初始化固定形状的数组（如全0占位、全1初始化）。
3. 基于数值范围生成： 生成数值序列，常用于模拟时间序列、坐标网络等。
4. 特殊矩阵生成： 数学运算专用（如线性代数中的单位矩阵）。
5. 随机数组生成： 模拟实验数据、初始化神经网络权重等场景。
6. 高级构造方法： 处理非结构化数据（如文件、字符串）或通过函数生成复杂数组。

In [31]:
# 基础的创建方法
arr = np.array([1,2,3], dtype=np.float64) # 相当于list=[1, 2, 3], arr=np.array(list)
print(arr.ndim)
print(arr)

1
[1. 2. 3.]


In [34]:
# copy
arr1 = np.copy(arr) # 元素跟原始的数组相同，但是不是一个数组
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [37]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3), dtype=int) # 2行3列
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [39]:
# 全1
arr = np.ones((2,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [41]:
# 未初始化
arr = np.empty((4,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [42]:
arr = np.full((3,4), 2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [43]:
arr1 = np.zeros_like(arr) # 同理还有empty_like, full_like, ones_like
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [47]:
# 等差数列 2 4 6 8 10
arr = np.arange(2, 11, 2) # start, end, step(步长)
print(arr)

[ 2  4  6  8 10]


In [49]:
# 等间隔数列
app = np.linspace(1, 10, 5) # 每个数字之间的间隔是一样的
print(app)

[ 1.    3.25  5.5   7.75 10.  ]


In [53]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [55]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2) # 取了0，2，4这3个数，以2为底的结果
print(arr)

[ 1.  4. 16.]


In [59]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [62]:
# 对角矩阵： 主对角线上非零的数字，其他的数字为0
arr = np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [63]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.9913032  0.20531812 0.61394881]
 [0.09540605 0.83921191 0.11742997]]


In [64]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (2,3))
print(arr)

[[5.7281343  5.38087844 5.80806109]
 [4.47735845 5.47513786 3.97151436]]


In [65]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2,3))
print(arr)

[[16 15 13]
 [16  3 27]]


In [71]:
# 生成随机数列（正态分布）
# 两边小，中间大
arr = np.random.randn(2,3)
print(arr)

[[ 0.93946935 -0.97848104  0.50309684]
 [ 0.40641447  0.32346101 -0.49341088]]


In [70]:
# 设置随机种子
np.random.seed(20) # 保证生成的数组是一样的，种子和数组是有关联的
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


**4.ndarray的数据类型**

布尔类型 bool

整数类型 int unit

浮点数 float

复数 complex

In [74]:
arr = np.array([1,0,3,0], dtype='bool')
print(arr)

[ True False  True False]


In [75]:
arr = np.array([1,0,3,0], dtype=np.int8) #int8的范围是-128～127
print(arr)

[1 0 3 0]


**5.ndarray的索引与切片**

基本索引： 通过整数索引直接访问元素。索引从0开始

行/列切片： 使用冒号：切片语法选择行或列的子集

连续切片： 从起始索引到结束索引按步长切片

使用slice函数： 通过slice（start, stop, step）定义切片规则

布尔索引： 通过布尔条件筛选满足条件的元素，支持逻辑运算符&、｜

In [79]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr)
print(arr[10])
print(arr[:]) # 获取全部的数据
print(arr[2:5]) # start:end+1 左闭右开
print(arr[slice(2, 15, 3)]) # start, end, step
print(arr[(arr>10) & (arr<70)]) # 布尔索引

[61 85 31 37  9 49 20 49 96 54 11 39 10 61 61 24 53 97 77 79]
11
[61 85 31 37  9 49 20 49 96 54 11 39 10 61 61 24 53 97 77 79]
[31 37  9]
[31 49 96 39 61]
[61 31 37 49 20 49 54 11 39 61 61 24 53]


In [80]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4,8))
print(arr)

[[96 55 82 74 28 40 88 10]
 [15 32 57 57 59 80 28 51]
 [75 70  3 58 24 96 26 42]
 [10 67 16 66 31 89 50 41]]


In [90]:
print(arr[1,4]) # 索引 
print(arr[1,2:5])
print(arr[arr>50])
print(arr[2]) # 第2行所有数据，也可以写成arr[2,:]
print(arr[2][arr[2]>50]) # 嵌套，过滤行数据
print(arr[:,3])

59
[57 57 59]
[96 55 82 74 88 57 57 59 80 51 75 70 58 96 67 66 89]
[75 70  3 58 24 96 26 42]
[75 70 58 96]
[74 57 58 66]


**6.ndarray的运算**

In [95]:
# 算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [94]:
c = [1, 2, 3]
d = [4, 5, 6]
print(c + d)
for i in range(len(c)):
    d[i] = d[i] + c[i]
print(d)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [96]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [97]:
# 数组与标量之间的算数运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [98]:
# 广播机制
# 同一维度：相同、1
a = np.array([1, 2, 3]) # 1*3
b = np.array([[4],[5],[6]]) # 3*1
print(a + b)
'''a
1 2 3
1 2 3
1 2 3
b
4 4 4
5 5 5
6 6 6
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]


'a\n1 2 3\n1 2 3\n1 2 3\nb\n4 4 4\n5 5 5\n6 6 6\n'

In [100]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a * b) # 对应数字相乘
print(a @ b) # 矩阵乘法

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


### 二、numpy中的常用函数 ###

**1.基本数学函数**

In [103]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [104]:
# 计算指数 e^x = y
print(np.exp(1))

2.718281828459045


In [105]:
# 计算自然对数 ln y = x
print(np.log(2.71))

0.9969486348916096


In [106]:
# 计算正弦值、余弦值
print(np.sin(-1))
print(np.cos(np.pi))

-0.8414709848078965
-1.0


In [107]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [108]:
# 计算a的b次幂
print(np.power(arr,2))

[1 1 4 9]


In [109]:
# 四舍五入
print(np.round([3.2, 4.5, 8.1, 9.6]))

[ 3.  4.  8. 10.]


In [110]:
# 向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [112]:
# 检测缺失值NaN
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

**2.统计函数**

求和、计算平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差

In [114]:
arr = np.random.randint(1, 20, 8)
print(arr)

[15  6  4 12 10  2  3 14]


In [116]:
# 求和
print(np.sum(arr))

66


In [118]:
# 计算平均值
print(np.mean(arr))

8.25


In [121]:
# 计算中位数
# 奇数： 排序后中间的数值
# 偶数： 中间的两个数的平均值
print(np.median(arr))
print(np.median([1, 2, 4]))
print(np.median([1, 2, 4, 8]))

8.0
2.0
3.0


In [124]:
# 计算方差、标准差
# 1, 2, 3的平均值 2
# 方差：((1-2)^2 + (2-2)^2 + (3-2)^2) / 3 = 0.66 标准差：方差开方
arr1 = np.array([1,2,1,2,1,1,1,2])
arr2 = np.array([1,0,3,0,0,0,4,2])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))
print(np.std(arr1))
print(np.std(arr2))

1.375
1.25
0.234375
2.1875
0.4841229182759271
1.479019945774904


In [126]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[15  6  4 12 10  2  3 14]
15 0
2 5


In [128]:
# 分位数
# 中位数
print(np.median([1, 2, 3]))
print(np.median([1, 2, 3, 4]))
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
print(np.median(arr))
# ___________________
# 44   47    64    67
# 0.25 * 3 = 0.75
# (47 - 44) * 0.75 = 2.25 + 44 = 46.25
print(np.percentile(arr,25)) # 所有数字的比例

2.0
2.5
[44 47 64 67]
55.5
46.25


In [129]:
# 累积和、累积积
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


**3.比较函数**

比较是否大于、小于、等于

逻辑与、或、非

检查数组中是否有一个True，是否所有的都为True，自定义条件

In [131]:
# 是否大于
print(np.greater([3,4,5,6,7],4))
# 是否小于
print(np.less([3,4,5,6,7,8],4))
# 是否等于
print(np.equal([3,4,5,6,7,8],4))
print(np.equal([3,4,5],[4,4,4]))

[False False  True  True  True]
[ True False False False False False]
[False  True False False False False]
[False  True False]


In [133]:
print(np.logical_and([1,0], [1,1]))
print(np.logical_not([1,0]))
print(np.logical_or([0,0], [1,1]))

[ True False]
[False  True]
[ True  True]


In [136]:
# 检查元素是否至少有一个元素为True
print(np.any([0,1,0,0,0]))
print(np.any([0,0,0,0,0]))
# 检查是否全部元素为True
print(np.all([1,1]))
print(np.all([1,0]))

True
False
True
False


In [137]:
# 自定义条件
# print(np.where(条件，符合条件，不符合条件))
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr>3, arr, 0))

[0 0 0 4 5]


In [139]:
arr = np.array([1,2,3,4,5])
print(np.where(arr<3, 1, 0))

[1 1 0 0 0]


In [141]:
score = np.random.randint(50, 100, 20)
print(score)
print(np.where(score>=60, '及格', '不及格'))

[63 58 59 70 66 55 65 97 50 68 85 74 99 79 69 69 64 89 82 51]
['及格' '不及格' '不及格' '及格' '及格' '不及格' '及格' '及格' '不及格' '及格' '及格' '及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '不及格']


In [142]:
print(np.where(
    score < 60, '不及格', np.where(
        score < 80, '良好', '优秀')
))

['良好' '不及格' '不及格' '良好' '良好' '不及格' '良好' '优秀' '不及格' '良好' '优秀' '良好' '优秀' '良好'
 '良好' '良好' '良好' '优秀' '优秀' '不及格']


In [143]:
# np.select(条件， 返回的结果)
print(np.select([score>80, (score>60)&(score<80), score<60], 
                ['优秀', '良好', '不及格'],
               default = '未知'))

['良好' '不及格' '不及格' '良好' '良好' '不及格' '良好' '优秀' '不及格' '良好' '优秀' '良好' '优秀' '良好'
 '良好' '良好' '良好' '优秀' '优秀' '不及格']


**4.排序函数**

In [145]:
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(arr.sort()) # 这个输出的是arr.sort()这个内容，而不是arr的内容
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
None
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


In [146]:
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(np.sort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [147]:
# 去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [150]:
# 数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [153]:
# 数组的分割
print(np.split(arr, 5)) # 这里的数字只能写等分的
print(np.split(arr, [6, 12, 18])) # 这里可以写出具体的位置，不用等分

[array([45, 48, 65, 68]), array([68, 10, 84, 22]), array([37, 88, 71, 89]), array([89, 13, 59, 66]), array([40, 88, 47, 89])]
[array([45, 48, 65, 68, 68, 10]), array([84, 22, 37, 88, 71, 89]), array([89, 13, 59, 66, 40, 88]), array([47, 89])]


In [154]:
# 调整数组的形状
print(np.reshape(arr, [4,5])) # 4行5列，也是需要能等分的

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


### 综合练习 ###

In [162]:
"""
题目 1: 温度数据分析
某城市一周的最高气温（摄氏度）为[28, 30, 29, 31, 32, 30, 29].
- 计算平均气温、最高气温和最低气温
- 找出气温超过30的天数
"""
import numpy as np
temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(temps)
print('平均气温:', '%.3f' %np.mean(temps)) # 保留3位小数
print('最高气温:', np.max(temps))
print('最低气温:', np.min(temps))
print('气温超过30的天数:', len(temps[temps>30]))
print(np.where(temps>30, temps, 0))
print(np.cumsum(np.where(temps>30,1,0))[-1]) # 取最后一个数
print(np.count_nonzero(temps>30))

[28 30 29 31 32 30 29]
平均气温: 29.857
最高气温: 32
最低气温: 28
气温超过30的天数: 2
[ 0  0  0 31 32  0  0]
2
2


In [167]:
"""
题目 2: 学生成绩统计
某班级5名学生的数学成绩[85， 90， 78， 92， 88]。
- 计算成绩的平均分、中位数和标准差。
- 将成绩转换为百分制（假设满分为100）
"""
score = np.array([85, 90, 78, 92, 88])
print(score)
print(np.sort(score))
print('平均分:', np.mean(score))
print('中位数:', np.median(score))
print('标准差: %.3f' % np.std(score))
print(score/10)

[85 90 78 92 88]
[78 85 88 90 92]
平均分: 86.6
中位数: 88.0
标准差: 4.883
[8.5 9.  7.8 9.2 8.8]


In [169]:
"""
题目 3: 矩阵运算
给定矩阵 A = [[1,2],[3,4]] 和 B = [[5, 6], [7, 8]]
- 计算 A + B 和 A * B （逐元素乘法）。
- 计算 A 和 B 的矩阵乘法（点积）。
"""
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A + B)
print(A * B)
print(A @ B)
print(np.dot(A, B))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [173]:
"""
题目 4: 随机数据生成
生成一个（3, 4)的随机整数数组，范围[0, 10)
- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为 -1。
"""
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print('每列的最大值:', np.max(arr, axis=0)) #axis轴 axis=0列 axis=1行
print('每行的最小值:', np.min(arr, axis=1))
print(np.where(arr%2==1, -1, arr))
arr[arr%2==1]=-1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值: [7 9 7 6]
每行的最小值: [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [182]:
"""
题目 5: 数组变形
创建一个 1 到 12 的一维数组，并转换为(3, 4)的二维数组。
- 计算每行与每列的平均值。
- 将数组展平为一维数组。
"""
arr = np.arange(1,13)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)
print('每行的和', np.sum(arr, axis=1))
print('每列的平均值', np.mean(arr, axis=0))
arr = np.reshape(arr, (12))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和 [10 26 42]
每列的平均值 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [184]:
"""
题目 6: 布尔索引
生成一个(5, 5)的随机数组，范围[0, 20)
- 找出数组中大于10的元素
- 将所有大于10的元素替换为0
"""
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print(arr[arr>10])
arr = np.where(arr>10, 0, arr)
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [186]:
"""
题目 7: 统计函数应用
某公司6个月的销售额（万元）为[120, 135, 110, 125, 130, 140]。
- 计算销售额的总和、均值和方差
- 找出销售额最高的月份和最低的月份
"""
money = np.array([120, 135, 110, 125, 130, 140])
print('总和:', np.sum(money))
print('平均值:', np.mean(money))
print('方差:', np.var(money))
print('销售额最高的月份:', )
print('销售额最低的月份:', )
print('最高的月份', np.argmax(money)+1)
print('最低的月份', np.argmin(money)+1)

总和: 760
平均值: 126.66666666666667
方差: 97.22222222222223
销售额最高的月份:
销售额最低的月份:
最高的月份 6
最低的月份 3


In [187]:
"""
题目 8: 数组拼接
给定 A = [1, 2, 3] 和 B = [4, 5, 6]
- 将 A 和 B 水平拼接为一个新数组。
- 将 A 和 B 垂直拼接为一个新数组。
"""
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate([A, B])
print(C)
print(np.reshape(C, (2, 3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [197]:
"""
题目 9: 唯一值与排序
给定数组 [2, 1, 2, 3, 1, 4, 3]
- 找出数组中的唯一值并排序
- 计算每个唯一值出现的次数
"""
arr = np.array([2, 1, 2, 3, 1, 4, 3])
u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)
d = []
for i in range(len(u_arr)):
    d = d + [len(arr[arr==u_arr[i]])]
print(d)

[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


In [199]:
"""
题目 10: 综合应用
某商店 5 天的销售额（万元）和成本（万元）如下：
销售额： [20, 25, 22, 30, 28]
成本： [15, 18, 16, 22, 20]
- 计算每天的利润（销售额 - 成本）。
- 计算利润的平均值和标准差。
- 找出利润最高的天数。
"""
money = np.array([20, 25, 22, 30, 28])
a = np.array([15, 18, 16, 22, 20])
b = money - a
print('每天的利润:', a)
print('利润的平均值:', np.mean(b))
print('利润的标准差:', np.std(b))
print('利润最高的天数:', len(b[b==np.max(b)]))

每天的利润: [15 18 16 22 20]
利润的平均值: 6.8
利润的标准差: 1.16619037896906
利润最高的天数: 2
